/**
 * Generated by Gas3 v2.0.0 (Granite Data Services).
 *
 * NOTE: this file is only generated if it does not exist. You may safely put
 * your custom code here.
 */

package com.i 
{
	import mx.collections.ArrayCollection;
	
    [Bindable]
    [RemoteClass(alias="com.i.Post")]
    public class Post extends PostBase
    {

    }
}