recaptcha {
    // These keys are generated by the ReCaptcha service
	publicKey = "6LcVXAkAAAAAAKgu9rdeeT2IleaAl71PGL5TBYTt"
	privateKey = "6LcVXAkAAAAAAOMbVAUwQahds1H1d9EogbmdCCzj"

	// Include the noscript tags in the generated captcha
	includeNoScript = true
}

environments {
  development {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = false
    }
  }
  production {
    recaptcha {
      // Set to false to disable the display of captcha
      enabled = true

      // Communicate using HTTPS
      useSecureAPI = true
    }
  }
}